### ISSUE TITLE
v1.4.0 causes issues with vimtex delimiter matching for $ character

### ISSUE THREAD

**Issue by boseranit** [lifepillar/vim-solarized8#97] opened 2022-06-29 13:38 UTC
After the update to v1.4.0, several problems occured with my vimtex setup:
1. vimtex imaps stopped working in inline math in tex files (between two $ characters)
2. delimiter matching for the character $ was suddenly incorrect - it always matched with the previous $ even if the matching one was ahead
3. ultisnip snippets stopped working inline. 

All of this because of the color scheme! 
I spent over 3 hours uninstalling and reinstalling every plugin, downgrading plugin and neovim versions, and removing one plugin at a time. But finally I tried using a minimal.vim file and added a line at a time when I finally found out it was caused by this colorscheme. And indeed checking out v1.3.0 fixed all the problems I was having! 
I'm not sure what has been done in v1.4.0, but it is certainly messing with the delimiter matching for $ in vimtex

**Comment by lifepillar** [comment] 2022-06-30 10:53
That sounds weird. Can you please post your minimal vimrc to reproduce the issue, and also provide more details on your environment (OS, Vim version, terminal).

**Comment by boseranit** [comment] 2022-06-30 11:05
This can be reproduced in the following way. I already have vimtex installed using vim-plug, and this same problem also occurs with older versions of vimtex. Clone the vim-solarized8 repo into Neovim\share\nvim\runtime\pack\dist\opt
Then the issue described only happens with v1.4.0 of this color scheme

Minimal.vim file: 
```
" Vim-plug
call plug#begin('$HOME/AppData/Local/nvim/plugged')
Plug 'lervag/vimtex'

call plug#end()
" 'filetype plugin indent on' already called in plug#end()

syntax enable
set background=dark
colorscheme solarized8_high
```
with minimal tex file
```
\documentclass[11pt]{article}

\begin{document}

\section{Question 1}
$a$ and $b$
\[\alpha\]

\end{document}
```

And I tested with nvim -u minimal.vim minimal.tex
Here's what I got from :VimtexInfo

System info:
  OS: ASUS-TUF-A15 (Microsoft Windows 10 Home)
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: \\.\pipe\nvim-22768-0

VimTeX project: test
  base: test.tex
  root: C:\Users\boser\OneDrive\Assignments\Test
  tex: C:\Users\boser\OneDrive\Assignments\Test\test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: build
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile

**Comment by lifepillar** [comment] 2022-07-03 15:00
Sorry for coming back late on this. It took me some time to figure this out.

I can reproduce your issues and I have found the cause. The issue is Nvim-specific and appears only if the color scheme is loaded in `init.vim`. Vim is not affected, and if the color scheme is loaded manually after starting Nvim, I don't have any issues. So, this looks to me like a bug in either Nvim or Vimtex (or both).

A workaround consists in adding `let g:solarized_extra_hi_groups = 0` to your config file before loading the color scheme.

The cause seems to be this line in `Solarized 8`:

```
hi texmathzonex guifg=#b58900 guibg=NONE gui=NONE cterm=NONE
```

By default, `texmathzonex` is linked to `Special`, but when `g:solarized_extra_hi_groups` is `1` (which is the new default in v1.4.0) `texmathzonex` is defined as above.

So, this is *not* a Solarized 8 issue: you may as well reproduce it with Vim's default color scheme: just add the highlight definition above to your config file:

```
" Vim-plug
call plug#begin('$HOME/AppData/Local/nvim/plugged')
Plug 'lervag/vimtex'

call plug#end()
" 'filetype plugin indent on' already called in plug#end()

syntax enable
hi texmathzonex guifg=#b58900 guibg=NONE gui=NONE cterm=NONE
```
I suggest that you report this to Vimtex's developers, who can most likely figure out whether the issue depends on their plugin or Nvim is to blame.

NOTE: I have not installled Ultisnips, so I can't tell for sure whether the workaround above also fixes Ultisnips problems. But I believe that the cause is the same or similar.

**Comment by boseranit** [comment] 2022-07-04 03:37
Thanks so much for taking the time to identify the issue and a providing a workaround. I'll report it to vimtex developers then.

**Comment by lifepillar** [comment] 2022-07-04 07:51
Cool. I assume that the workaround works for you, too, then, and I am closing this. Feel free to reopen if necessary.

**Closed as completed by lifepillar** 2022-07-04 07:51 UTC
