### ISSUE TITLE
html tags are green, draws too much attention

### ISSUE THREAD

**Issue by khangal** [lifepillar/vim-solarized8#32] opened 2018-01-09 03:09 UTC
How can I change it? I want tag colors same as 'altercation/vim-colors-solarized'.

**Comment by lifepillar** [comment] 2018-01-09 10:04
Have you tried to set `g:solarized_extra_hi_groups` to `1`?

Recent versions of Solarized 8 avoid defining filetype-specific highlight groups by default because of [a long standing issue](https://github.com/altercation/solarized/issues/102) caused by such definitions in colorschemes.

**Comment by lifepillar** [comment] 2018-01-21 16:43
I'm closing this. Feel free to re-open if the proposed solution does not work for you.

**Closed as completed by lifepillar** 2018-01-21 16:43 UTC
