### ISSUE TITLE
cursorline doesn't highlight some characters

### ISSUE THREAD

**Issue by mooreye** [lifepillar/vim-solarized8#95] opened 2022-03-27 17:36 UTC
![2022-03-27T19:30:10,988288967+02:00](https://user-images.githubusercontent.com/93423596/160293474-7ac61ec8-43fd-40fb-8585-8923b2473aa7.png)
I trimmed my `init.vim` to only the lines visible on the screen and as you can see, the ` ` and `=...` are not highlighted with cursorline. It seems to only happen there though, in bash scripts everything seems fine. Without theme everything is highlighted.

**Comment by lifepillar** [comment] 2022-03-27 18:36
I cannot reproduce it. Which terminal? Which OS? Which Vim version?

**Comment by mooreye** [comment] 2022-03-28 10:54
- GNOME Terminal 3.42.2 using VTE 0.66.2
- Fedora 35
- neovim 0.6.1

**Comment by lifepillar** [comment] 2022-03-29 11:49
Ok, reproducible with Neovim. This should be fixed in the current master. Feel free to reopen if that is not the case.

Thanks for reporting!

**Closed as completed** 2022-03-29 11:49 UTC
