### ISSUE TITLE
Solarized transparent is broken in Alacritty  in new v3 template

### ISSUE THREAD

**Issue by phongnh** [lifepillar/vim-solarized8#105] opened 2023-06-16 09:37 UTC
It seems that Solarized transparent is broken in new v3 template with Alacritty. Or some settings are need to be updated for Solarized transparent v3 with Alacritty?

After this commit `bcd4e74e9850fd59ee0294a5c3ae958ed535cc52`, Solarized transparent does not work any more.

Here are my settings.

```
set t_Co=16
let g:solarized_italics  = 1
let g:solarized_termtrans  = 1
let g:solarized_extra_hi_groups = 1
```

Screenshots for reproduce:

https://github.com/lifepillar/vim-solarized8/assets/438791/709e0116-fc02-4ee8-aaec-675c43c76967

After resetting to this commit `bcd4e74e9850fd59ee0294a5c3ae958ed535cc52`

https://github.com/lifepillar/vim-solarized8/assets/438791/320ddfab-2f05-40d3-90a3-a410bc9b8d38

Thanks for your awesome colorscheme.

**Comment by lifepillar** [comment] 2023-06-16 20:54
I cannot reproduce it using Alacritty 0.12.1 and Vim 9.0.1499 on macOS. Can you provide more details about your environment (OS, Vim version) and a full `vimrc` to reproduce this issue with `vim -u vimrc`?

**Comment by phongnh** [comment] 2023-06-17 03:53
I tried to reproduce with Alacritty 0.12.1 and Vim 9.0.1600 on macOS (Ventura 13.4 (M1)).

<img width="702" alt="image" src="https://github.com/lifepillar/vim-solarized8/assets/438791/d1b109bf-5d56-41a9-9cc6-838eaf926da7">

Here is the minimal vimrc I used

```vim
set encoding=utf-8
scriptencoding utf-8

set nocompatible
set cmdheight=10
set termguicolors
set runtimepath^=~/.vim/plugged/vim-solarized8

syntax on
filetype plugin indent on

let g:solarized_termtrans = 1
set background=dark
colorscheme solarized8
```

With vim-solarized8's latest commit

<img width="1512" alt="Screenshot 2023-06-17 at 10 51 59" src="https://github.com/lifepillar/vim-solarized8/assets/438791/d6c26370-58ed-4927-a3ec-61fd5507e1a9">

With vim-solarized8's commit `bcd4e74e9850fd59ee0294a5c3ae958ed535cc52`

<img width="1512" alt="Screenshot 2023-06-17 at 10 44 37" src="https://github.com/lifepillar/vim-solarized8/assets/438791/91e2466b-6600-4ef8-8a30-1811e2ace0c5">

**Comment by lifepillar** [comment] 2023-06-17 09:56
Thanks for the detailed report! I had missed setting `termguicolors`.

I see what the problem is. I will look for a fix. For now, you may revert to a previous commit or release.

**Comment by lifepillar** [comment] 2023-06-17 10:58
This is fixed in the current master. Thanks for contributing!

**Closed as completed** 2023-06-17 10:57 UTC

**Comment by phongnh** [comment] 2023-06-17 19:05
Great! Thanks for your fix.
