### ISSUE TITLE
Visual mode is very subtle

### ISSUE THREAD

**Issue by bengolds** [lifepillar/vim-solarized8#16] opened 2017-06-20 22:20 UTC
Using Nvim 0.2 and hterm:

![screenshot 2017-06-20 at 4 19 31 pm](https://user-images.githubusercontent.com/446007/27358509-428d8f60-55d4-11e7-912a-a12d2e1e2ebe.png)

The top half is selected in visual mode; the background doesn't change at all, only the foreground changes to be uniform. On certain files with very little syntax highlighting, this is very hard to see. Is this indented?

**Comment by lifepillar** [comment] 2017-06-21 17:59
That is not the way it should look, no matter which variant you use. It should look like this:

<img width="474" alt="visual_mode_solarized8" src="https://user-images.githubusercontent.com/1193314/27399113-0241ecc4-56bc-11e7-8b62-ac33b17b45af.png">

Maybe your terminal is overriding the color for selected text? If not, does your terminal support true colors?

**Comment by bengolds** [comment] 2017-06-21 19:37
Hmm, thanks for helping look at that. I'll give you as much info as I've got:

I think I'm good on the truecolor front:
![screenshot 2017-06-21 at 1 34 39 pm](https://user-images.githubusercontent.com/446007/27403103-6ac89fb2-5686-11e7-9b6a-f3e4d82ab3b9.png)

`:echo termguicolors1 shows "1"

This is what I get for `:hi Visual`
![screenshot 2017-06-21 at 1 36 02 pm](https://user-images.githubusercontent.com/446007/27403145-96ab057a-5686-11e7-825b-5e91a9822b80.png)

And lastly, I have the issue no matter what the terminal color scheme is. Any suggestions?

**Comment by lifepillar** [comment] 2017-06-22 06:14
Apparently, all is fine from what you show. I'd blame the terminal. Could you try a different one? Also, can you provide a link to the terminal you are using (there is more than one terminal called “hterm”), so I may test it?

**Comment by bengolds** [comment] 2017-06-22 14:52
I think you're right -- it might be the terminal. When launched in gnome-term with the exact same nvim config, it looks right.. The hterm I'm using [is the default terminal on chrome os](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm). You can probably simulate it using the [secure shell](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo) chrome extension.

**Comment by bengolds** [comment] 2017-06-22 15:12
Or, [hyper](https://github.com/zeit/hyper) might have the same problem.

**Comment by bengolds** [comment] 2017-06-22 15:24
Quick update: so far, it seems the culprit is that gui=reverse doesn't work on my terminal. More investigation to come!

**Comment by bengolds** [comment] 2017-06-22 16:09
Update #2: gui=reverse does generally work on my terminal, but is incompatible with guibg. It seems like that is sort of edge-case behavior; I'm not sure they're supposed to be set at the same time. For now, I'll take a stab at making a compatible version. @lifepillar do you have a recommended way to do this?

**Comment by lifepillar** [comment] 2017-06-22 16:20
>I'm not sure they're supposed to be set at the same time.

`guibg` sets the foreground color when `gui=reverse`. So I'd say: yes, they are supposed to be used together.

Btw, how does visual selection look like in Vim?

**Comment by lifepillar** [comment] 2017-06-22 16:33
With hyper, the color scheme looks fine if I use [this configuration](https://gist.github.com/nkzawa/970f75de0f9f8b05524d99452dfabd54).

Have you tried setting the 16 color palette of your terminal to Solarized (even if the terminal supports true colors)?

**Comment by bengolds** [comment] 2017-06-22 16:36
In Vim 8.0 with termguicolors I have the same problem. Looks like it might be a terminal problem (for me it reproes in hyper.is), although it's strange that `ctermbg` and `cterm=reverse` work fine. 

My configuration (crosh uses a diff screen for configuration) has these color overrides, from https://github.com/giraj/solarized-crosh: `["#073642","#dc322f","#859900","#b58900","#268bd2","#d33682","#2aa198","#eee8d5","#002b36","#cb4b16","#586e75","#657b83","#839496","#6c71c4","#93a1a1","#fdf6e3"]`

**Comment by bengolds** [comment] 2017-06-22 16:40
Even stranger, I have the same problem in hyper with the exact same configuration as you!

**Comment by lifepillar** [comment] 2017-06-22 16:42
>Even stranger, I have the same problem in hyper with the exact same configuration as you!

Try to replace only the `color` section in hyper's default configuration.

**Comment by bengolds** [comment] 2017-06-22 16:45
Same problem. I'm gonna investigate my `.vimrc` file and see if there's interference there. What OS are you running hyper on?

**Comment by lifepillar** [comment] 2017-06-22 16:47
macOS.

**Comment by bengolds** [comment] 2017-06-22 16:52
I'm running on Ubuntu. So far no dice on stripping down my vimrc. I'll try it on macOS in a few days. Thanks for the help so far! Also, if you have any info on the escape codes `guibg` and `gui=reverse` send, I can start filing bugs where necessary!

**Comment by lifepillar** [comment] 2017-09-21 18:20
Eventually, I could reproduce this with Hyper 1.4.7, with `termguicolors` set. Apparently, the `reverse` option has no effect in that terminal. I am closing this because this is a terminal's issue, not something that can be fixed in the colorscheme. As for the escape codes sent when `reverse` is set, I'm afraid I can't help, but you may ask in Vim's mailing list if you like.

**Closed as completed by lifepillar** 2017-09-21 18:20 UTC
