### ISSUE TITLE
Title group inconsistently colored between gui/non-gui apps

### ISSUE THREAD

**Issue by jreichert** [lifepillar/vim-solarized8#107] opened 2023-08-01 22:55 UTC
I am working from a base version of EverVim that I have heavily customized, and it is bundled with a very old version of vim-solarized8 (I believe 0.7).  When I updated it to use 1.5.1, all of my titles in Vimwiki changed from yellow (#b58900) to orange (#cb4b16) using the "Title" highlight group.  I was using 'solarized8_dark_high" in 0.7, and now I am using "solarized8_high" in 1.5.1.  

The logic to determine the color of the Title group changed between those versions.  In addition to my personal preference for the old Title color (the default was changed from #b58900 to #cb4b16), the behavior in the new workflow is inconsistent.  Setting `solarized_visibility` to "high" in a gui app changes it to #b58900, but if you aren't in a gui app then setting `solarized_visibility` has no effect.   

For test purposes, I'm using the following:
* terminal: NeoVim on a Mac with iTerm2 (which has `termguicolors` set)
* gui: NeoVim-qt on Mac  

I can see two different ways to resolve this.

1. If there isn't an intentional rationale for having different colors in a gui app than in a terminal (provided that the latter can support the exact same colors), then you can change the logic to test for whether `termguicolors` is set instead of or in addition to testing `has ('gui_running')` (that's the route they took when solving [this similar issue](https://github.com/vim-airline/vim-airline/issues/2261) in Airline).  
2. If there is a specific reason for wanting colors to be different between gui apps and terminal apps (even if they support the same colors), then you could instead change the control flow so that `solarized_visibility` changes the title color in both gui apps and non-gui apps (even if it changes them to different things).

Looking at the code, the change was as follows (I'm only showing the delta for dark backgrounds but it is similar for light as well):

* Old: solarized_visibility=[none/high] -> **#b58900**; low -> #657b83
* New: **No 'gui_running'** -> #cb4b16; otherwise solarized_visibility=none -> #cb4b16, low -> #657b83, high -> #b58900

The bold sections above show what changed specifically that impacted me.  Previously #b58900 was the default, and that only changed if you explicitly set `solarized_visibility`.  Now the default for a non-gui app is #cb4b16 and there is no way to change that without explicitly overriding the highlight color in your vimrc. 

This raises a minor secondary issue.  In the original Solarized, `solarized_visibility` was only used to control the color of two groups: `SpecialKey` and `NonText`.  In Solarized8 it was changed to control several Spelling-related groups as well as Title.  The README doesn't really make it clear that this has changed, which threw me off when I was trying to diagnose the above; it just says it was inherited from the original Solarized, which led me to believe that it still only controlled the highlighting of those original two groups.  It would help to update the README to say that it controls more special characters than it did in the original plugin.

**Comment by lifepillar** [comment] 2023-08-02 21:27
Several differences have accumulated from the original Solarized, mostly to meet my own preferences, but also suggested by other users. Accurately reproducing the original Solarized has never been a goal of this project, and the interpretation of the original options is liberal.

That said, the effect of the options should not differ significantly between GUI and terminal (within the limits of the terminal color palettte). What you mention sounds like a regression: I will look into it.

**Comment by jreichert** [comment] 2023-08-03 17:46
Agreed there should be no effort to reimplement the original Solarized - I much prefer the current color palette at large.  Given that that is the case, it would be helpful in the README to clarify the role of `solarized_visibility` in Solarized8.

**Comment by lifepillar** [comment] 2023-08-03 20:06
>The logic to determine the color of the Title group changed between [v0.7 and v1.5.1]

Correct.

>all of my titles in Vimwiki changed from yellow (#b58900) to orange (#cb4b16) using the "Title" highlight group

That was an intentional change (see cd5e87ccfa6a782e8058255b91af94a45b7603e0 and https://github.com/lifepillar/vim-solarized8/issues/76).

>Setting solarized_visibility to "high" in a gui app changes it to #b58900,

Yes.

>but if you aren't in a gui app then setting solarized_visibility has no effect.

I cannot reproduce it in iTerm2, neither in Vim or Neovim (btw, if you are using Neovim, you should switch to the `neovim` branch if you haven't done so). 

The `Title` highlight group should be a shade of orange by default, and yellowish if you set `g:solarized_visibility="high"`, regardless of the environment. If you are seeing something different, please provide step-by-step instructions to reproduce it with a minimal vimrc.

Regarding the differences from the original Solarized, I will update the Readme.

**Comment by lifepillar** [comment] 2023-08-13 10:09
The Readme has been updated. I'm going to close this because I cannot reproduce any color inconsistency between GUI and terminal. Feel free to reopen (with more details) if that is still an issue on your side.

**Closed as completed by lifepillar** 2023-08-13 10:09 UTC
